"""语音运行时共享常量。"""

SERVER_SAMPLE_RATE_HZ = 16000
SERVER_CHANNELS = 1
SERVER_SAMPLE_WIDTH_BYTES = 2
MODEL_OUTPUT_SAMPLE_RATE_HZ = 24000
PLAYBACK_QUEUE_MAX = 256
UTTERANCE_PHOTO_CAPTURE_TIMEOUT_MS = 10000
OMNI_SEMANTIC_VAD_NO_AUTO_RESPONSE = "semantic_vad_no_auto_response"
OMNI_SEMANTIC_VAD_AUTO_RESPONSE_GRACE_SECONDS = 3.0
VOICE_TURN_INTENT_SIDECAR_WAIT_SECONDS = 3.0
VOICE_TURN_SHORT_PENDING_ASR_MAX_MS = 1800
